#!/usr/bin/env scheme-script
;; -*- mode: scheme; coding: utf-8 -*- !#
;; Copyright (c) 2026 Travis Hinkelman
;; SPDX-License-Identifier: MIT
#!r6rs

;; Builds passgen/words.scm, a list of common, human-readable English words.
;; A word is kept when it
;;   * ranks in the top N of both the US TV/film and English Wikipedia
;;     frequency lists from zxcvbn-chez (i.e., it is common in speech and print),
;;   * appears in the system dictionary (/usr/share/dict/words) in lowercase,
;;   * is 2-8 letters long, is plain a-z, and is not a common first name
;;     or on the blocklist.
;;
;; run this script with the following line in the terminal
;; scheme --script ./data-scripts/build-word-list.ss [path/to/zxcvbn-chez/data]

(import (chezscheme))

(define data-dir
  (let ([args (cdr (command-line))])
    (if (null? args) "../zxcvbn-chez/data" (car args))))

(define max-rank 20000)
(define min-length 3)
(define max-length 8)

;; the dictionary includes many obscure 2-letter words so only these are kept
(define two-letter-words
  '("am" "an" "as" "at" "be" "by" "do" "go" "he" "hi" "if" "in" "is" "it"
    "me" "my" "no" "of" "oh" "on" "or" "ox" "so" "to" "up" "us" "we"))

;; offensive or otherwise unsuitable words that survive the filters
(define blocklist
  '("ass" "bitch" "bitches" "bastard" "crap" "cunt" "damn" "dick" "dumb"
    "fag" "fuck" "fucked" "fucking" "gay" "hell" "hitler" "nazi" "nigger"
    "penis" "piss" "porn" "rape" "raped" "sex" "sexy" "shit" "slut" "suck"
    "sucks" "vagina" "whore" "kill" "killed" "killing" "kills" "murder"
    "suicide" "dead" "die" "died" "cum"
    ;; abbreviations, fragments, and proper nouns
    "abu" "aka" "bam" "bel" "cal" "cha" "col" "con" "dar" "dod" "dom" "dos"
    "dow" "eta" "gon" "ing" "kat" "lam" "las" "lew" "mar" "mas" "mil" "mon"
    "nat" "nee" "pac" "poe" "quo" "rio" "sac" "sen" "sic" "sri" "tha" "tor"
    "tri" "vis" "wah"))

(define (first-token line)
  (let ([n (string-length line)])
    (let loop ([i 0])
      (if (or (= i n) (char=? (string-ref line i) #\space))
          (substring line 0 i)
          (loop (+ i 1))))))

;; read the first `limit` tokens of a file into a hashtable (#f = no limit)
(define (read-tokens path limit)
  (let ([ht (make-hashtable string-hash string=?)])
    (call-with-input-file path
      (lambda (port)
        (let loop ([line (get-line port)] [rank 1])
          (unless (or (eof-object? line) (and limit (> rank limit)))
            (hashtable-set! ht (first-token line) rank)
            (loop (get-line port) (+ rank 1))))))
    ht))

;; ordered list of tokens from a ranked file
(define (read-ordered path limit)
  (call-with-input-file path
    (lambda (port)
      (let loop ([line (get-line port)] [rank 1] [out '()])
        (if (or (eof-object? line) (> rank limit))
            (reverse out)
            (loop (get-line port) (+ rank 1) (cons (first-token line) out)))))))

(define (data-path name) (string-append data-dir "/" name ".txt"))

(define tv-film   (read-ordered (data-path "us_tv_and_film") max-rank))
(define wikipedia (read-tokens (data-path "english_wikipedia") max-rank))
(define male      (read-tokens (data-path "male_names") #f))
(define female    (read-tokens (data-path "female_names") #f))
(define dict      (read-tokens "/usr/share/dict/words" #f))

(define (keep? word)
  (let ([n (string-length word)])
    (and (or (<= min-length n max-length) (member word two-letter-words))
         (for-all (lambda (c) (char<=? #\a c #\z)) (string->list word))
         (hashtable-contains? wikipedia word)
         (hashtable-contains? dict word)
         (not (hashtable-contains? male word))
         (not (hashtable-contains? female word))
         (not (member word blocklist)))))

(define (dedupe sorted)
  (cond [(or (null? sorted) (null? (cdr sorted))) sorted]
        [(string=? (car sorted) (cadr sorted)) (dedupe (cdr sorted))]
        [else (cons (car sorted) (dedupe (cdr sorted)))]))

(define words
  (dedupe (list-sort string<? (filter keep? tv-film))))

(when (file-exists? "passgen/words.scm")
  (delete-file "passgen/words.scm"))

(with-output-to-file "passgen/words.scm"
  (lambda ()
    (display ";; Generated by data-scripts/build-word-list.ss -- do not edit by hand.\n")
    (write `(define word-list (quote ,(list->vector words))))
    (newline)))

(printf "wrote ~a words to passgen/words.scm\n" (length words))
